### PR TITLE
Updated the value types to Integer

### PR DESCRIPTION
**Pull request by arunherb**
This commit is an updated value types for the 'slope', 'homogenity measure' and 'aspect' to integer.

### CODE REVIEW

**Comment by arunherb** [comment]
@javiersan18 - I have updated the value types for these concepts to 'integer'. Please approve this and merge this branch to main, so I can ask Walid to run the validation checks.

**Review by javiersan18 — APPROVED** [review]
Hi Arun, everything looks correct.

Cheers,
Javier

**Review by smguru — COMMENTED** [review]
changes are approved

**Comment by smguru** [comment]
the changes from float to Int

**Pull request merged**
