### PR TITLE
Vocabs Mapping_update-v2 - Fauna Aerial Surveys

### PR DESCRIPTION
**Pull request by arunherb**
Updated mapping of vocabs based on version -2 ; Need to review again once the protocols team make further changes

### CODE REVIEW

**Comment by junrongYu** [comment]
Hi @arunherb , are we going to pause this work cuz we don't have no latest protocols?

**Comment by arunherb** [comment]
@junrongYu - yes, you may ignore this branch for now. I'll update this once we get a clarity on the changes from the protocols team.

**Comment by junrongYu** [comment]
Hi @arunherb , thanks for the updates, can you please have a look at following:

1. There is no updates in attributes / OPs collection files, does that mean there is no new attribute/OP in this module? I guess the new attribute concept `aircraft average ground speed` should be added?
2. Also, the prefLabels of some concepts/collections have been updated but file names and paths in `schema:url` are not updated, can you please update them? like the attribute `aircraft business name`, `line transect - sampling distance`, `strip transect - fixed width` etc..
3. In LUT file `line transect - distance sampling categories`, notations are after predicate `skos:notation`, can you please change it to `urnp:conceptNotation`? `skos:notation` is for Concept, not Concept Metadata.

Thanks!

**Comment by arunherb** [comment]
> Hi @arunherb , thanks for the updates, can you please have a look at following:
> 
> 1. There is no updates in attributes / OPs collection files, does that mean there is no new attribute/OP in this module? I guess the new attribute concept `aircraft average ground speed` should be added?
> 2. Also, the prefLabels of some concepts/collections have been updated but file names and paths in `schema:url` are not updated, can you please update them? like the attribute `aircraft business name`, `line transect - sampling distance`, `strip transect - fixed width` etc..
> 3. In LUT file `line transect - distance sampling categories`, notations are after predicate `skos:notation`, can you please change it to `urnp:conceptNotation`? `skos:notation` is for Concept, not Concept Metadata.
> 
> Thanks!

Done. I have made additional changes to some concepts, as you'll see.

**Comment by junrongYu** [comment]
Hi @arunherb , thanks for the updates, there is a typo in prefLabel of attribute `aircraft seat position`, can you please fix it? Also, are there any new attributes or OPs to be added in this module? if so, can you please add them? Thanks!

**Comment by junrongYu** [comment]
Hi @arunherb , thanks for the updates, can you please fix following issues:
In metadata file of OP `field species name`, feature type should be `animal population`, value type is `tern:Text`.
In metadata file of OP `distance to target fauna`, feature type should be `animal population`, and can you please add the categorical collection?
Thanks!

**Comment by arunherb** [comment]
> Hi @arunherb , thanks for the updates, can you please fix following issues: In metadata file of OP `field species name`, feature type should be `animal population`, value type is `tern:Text`. In metadata file of OP `distance to target fauna`, feature type should be `animal population`, and can you please add the categorical collection? Thanks!

Done

**Review by junrongYu — APPROVED** [review]

**Pull request merged**
