### PR TITLE
Improved method `vertebrate fauna`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #42

### CODE REVIEW

**Comment by junrongYu** [comment]
`Desktop study` not added because it's not part of field work.

**Comment by junrongYu** [comment]
TBD by protocols team, `Rationale` not provided.

**Comment by junrongYu** [comment]
The link of `interventions` method not added because it's not created yet.

**Comment by junrongYu** [comment]
`Table 3` in `Module overview` not added because: https://docs.google.com/document/d/120uys6XPWOkhUPLIxFKQTDMwBAnXj_gA/edit?disco=AAAAdSwg0B4

**Comment by junrongYu** [comment]
In sub protocol `fauna plot`, some steps and additional guidelines are missing: https://docs.google.com/document/d/120uys6XPWOkhUPLIxFKQTDMwBAnXj_gA/edit?disco=AAAAddFGeFM

**Comment by junrongYu** [comment]
Hi @arunherb , could you clarify where are `figure 5-1`, `figure 5-2`, `figure 5-3`, `figure 5-4`? In sub protocol `Identify, measure and release protocols`.

**Comment by junrongYu** [comment]
Hi @arunherb , could you clarify why these sub headings need hyperlinks? e.g. https://docs.google.com/document/d/120uys6XPWOkhUPLIxFKQTDMwBAnXj_gA/edit?disco=AAAAddFGeJU

**Comment by arunherb** [comment]
Hi @junrongYu ,

Here are some observations for the vertebrate fauna module:

1) Can we follow this structure like in other modules:
Contents (with jump-to section for each skos member)
- Introduction 
- Key definition
- Rationale
- Module Overview
-  Sub-protocols (skos:members)
- References
- Appendix

2) Hyperlink the "Plot selection and layout module" in the instructions under Fauna plot module.
3) Make sure other links are working. 

I'll have to review once again when I get the localhost system working on my computer. 

Thanks,
Arun

**Comment by arunherb** [comment]
@junrongYu ,

1) Add the contents (with jump to section for each heading)
2) can we also add the "jump-to section/hyperlink for each of the sub-modules that appear on the Module-overview table"?
3) hyperlink the "_plot selection and layout_" module in the instructions section in "fauna plot layout" sub-module and "_fauna plot layout and photographs protocols_" in "trapping protocols" and "_Identify, measure and release protocols_ " in "whole animal vouchering.
4) In whole animal vouchering sub-module, under instructions and procedures can we remove the numbers in pt 10, 14 and 15, i.e. "..see 6.1.3..." and instead just hyperlink the "additional guidelines", and "setting reptiles and frogs". (https://github.com/ternaustralia/dawe-rlp-vocabs/pull/194#issuecomment-1217439716)
5) Check Figure numbers and figure/appendices links are matching and working in sub-modules.

All others seems alright for this version.

**Comment by arunherb** [comment]
> 

@junrongYu 
1) Under Module overview under main page, there is a sentence "..._Section: Desktop study and pre-survey planning._". I think if we are not hyperlinking this to that particular section for this version, we should at least say the reader to "_(refer to the module PDF document)_". May be just add this in brackets.
2) Under Trapping protocols- please hyperlink the " (refer to Section 5 _Identify, measure and release protocols):_", and also remove the "Section 5" before that sub-module".
3)Under Additional Guidelines,> Ethical Considerations> pt E. Remove "Section 6" and just keep "Whole animal vouchering protocols", with hyperlink to that module. 
4) Under Instructions for Identify, measure and release protocols, pt 23please hyperlink "Whole animal vouchering protocols" and remove '6' from section; also hyperlink the "Ethical consideration..", pt 24; and under Additional Guidelines - Section C.
5) For this comment: https://github.com/ternaustralia/dawe-rlp-vocabs/pull/194#issuecomment-1217438925
I think Figure 5-1 is "Figure 19", Figure 5-2 is "Figure 20",  Figure 5 - 3 is "Figure 21" and Figure 5-4 is nothing but "Figure 21". Please hyperlink and update them accordingly.
6) Check the Bullet point for "Draft Key to Muridae of South Australia (Kemper undated)" under Additional Guidelines, D.
7) See the last sentence with a "Note:" under Bird Survey instructions- hyperlink "opportunistic observations module" here.

Others seem alright for this version.

Arun

**Review by edmondchuc — COMMENTED** [review]
LGTM. @junrongYu have @arunherb's concerns been fixed already?

**Comment by junrongYu** [comment]
> LGTM. @junrongYu have @arunherb's concerns been fixed already?

Hi @edmondchuc , yes, and those actions required from protocol team are documented here https://github.com/ternaustralia/dawe-rlp-vocabs/issues/203

**Review by edmondchuc — APPROVED** [review]

**Pull request merged**
