### PR TITLE
Fix methods `condition`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #36

### CODE REVIEW

**Comment by junrongYu** [comment]
The link of methods for `interventions` modules is not added cuz not created yet.

**Comment by junrongYu** [comment]
Needs `appendix 1` from protocols team.

**Comment by arunherb** [comment]
I think the condition module looks alright for this version. 

1) As in other modules, we need to check if all the links for figures and appendix are working.

**Comment by arunherb** [comment]
@junrongYu ,

1) In condition module, hyperlink the other modules that appear in module overview at the very beginning , such as "_Recruitment, Coarse woody debris and Fire_", and " Plot Selection and Layout module" in Field selection section and "cover" in pt 6 & 7.
2) "Appendix 1" mentioned in the additional guidelines in sub-modules is not linking appropriately.
all other links seems to be working fine for this version

**Comment by junrongYu** [comment]
Hi @arunherb ,

> "Appendix 1" mentioned in the additional guidelines in sub-modules is not linking appropriately.

This is because `appendix 1` is not provided.

**Review by edmondchuc — APPROVED** [review]

**Pull request merged**
