### PR TITLE
Signs_v2 - updates

### PR DESCRIPTION
**Pull request by arunherb**
Updated 'scat removal status' labels, in 'categorical concept file' and d metadata file; and renamed 'number of transects to be completetd'

### CODE REVIEW

**Comment by junrongYu** [comment]
Hi @arunherb , thanks for the updates, I have some questions:

- [ ] 1. What could be the value type of attributes `target species - deer`, `target species - wild dog`, is it boolean or LUT? Their app endpoint says it's LUT - https://core.vocabs.paratoo.tern.org.au/documentation#/Sign-based-active-plot-search-survey
- [ ] 2. For the new attribute `track photo ID`, we have a similar one `fauna track photo ID`, added in both `track station` and `vehicle track`, are they the same? https://linked.data.gov.au/def/nrm/3a69c876-d085-50c3-9a63-e3b7e82dcbc0
- [ ] 3. The attribute `number of observers` is removed from `off-plot`, should we remove it from all sub protocols?
- [ ] 4. URI https://linked.data.gov.au/def/nrm/301b5716-6a42-4426-8675-6c46343500fe is added in `off-plot` attributes collection file, but there is no concept file for it, do you know what it is?
- [ ] 5. OPs `number of warren entrances`, `number of den entrances`, `number of burrow entrances` have metadata files in `within-plot`, but OP URIs are not added to OP collection file, can you please add it?
- [ ] 6. In `off-plot`, the metadata file of OP `NVIS major vegetation group` has the wrong value of properties collection, can you please update it?
- [ ] 7. In `vehicle track`, can you please remove the URI of OP `number of individuals`? looks like it's replaced by new OP `attributable fauna count`
- [ ] 8. In `track station`, wrong URI is added for new OP `attributable fauna count`, can you please fix it in both collection file and metadata file? please also remove the URI of OP `number of individuals` in collection file.
- [ ] 9. In `within-plot` OP collection file, can you please replace https://linked.data.gov.au/def/nrm/0d7f98b2-9741-4dff-9849-5818ed64dbf4 (metadata URI of OP `den active status`) with https://linked.data.gov.au/def/nrm/0bc353aa-f678-5948-9fe7-6e0c39b2a6d6 (OP URI)
- [ ] 10. In `within-plot`, same for the OP `number of den entrances`, in OP collection file, can you please replace https://linked.data.gov.au/def/nrm/6f518640-e5cd-43f4-87ed-09550778ad9e with https://linked.data.gov.au/def/nrm/c497a8eb-f720-52a4-bc76-8ec1cf7d4cf2?
- [ ] 11. In `within-plot`, same for OP `number of warren entrances`, in the OP collection file, can you please replace https://linked.data.gov.au/def/nrm/be6b5545-d4a8-45e7-be0a-bc662a40af78 with https://linked.data.gov.au/def/nrm/26147520-7e7c-5b55-b2fa-197a02b7ab33
- [ ] 12. In `within-plot`, same for OP `number of burrow entrances`, in the OP collection file, can you please replace https://linked.data.gov.au/def/nrm/ea3232ea-13b6-5167-ae55-ad71ffcf3eb7 with https://linked.data.gov.au/def/nrm/dd805508-1eca-5b8b-b2e4-c51c1682e81e?
- [ ] 13. looks like the metadata files of OP `number of burrow entrances` in `within-plot` and `plot sign search` share the same URI, can you please generate a new UUID for one of them?
- [ ] 14. In `within-plot`, the metadata file of OP `number of warren entrances` has wrong value of protocolModule, can you please fix it?
- [ ] 15. for the new categorical concept `dingo - Canis lupus dingo`, we already have a concept `Dingo (Canis lupus dingo)`, are they the same?
- [ ] 16. for the new categorical concept `dingo-dog hybrid`, we have a concept `Dingo-Dog hybrid`, they look the same.
- [ ] 17. these 2 concepts in `categorical_concepts.ttl` looks the same - https://linked.data.gov.au/def/nrm/ffdac5da-c5a1-54e9-8e71-71c0503f4491 & https://linked.data.gov.au/def/nrm/69369a4b-1608-58c9-b37c-00758d401bf4
- [ ] 18. for new LUTs `deer species types` and `wild dog species types`, can you please add them to collection-members.ttl?
- [ ] 19. for LUT `deer species types`, can you please compare it with endpoint https://core.vocabs.paratoo.tern.org.au/api/lut-deer-pests, and add this to the source?
- [ ] 20. if the attribute `target species - deer`'s value type is IRI, can we link new LUT `deer species types` with it?
- [ ] 21. there is a metadata for categorical concept `deer` added in LUT `target species types`, but looks like the concept URI is not added to the collection, the collection URI in metadata is wrong. 
- [ ] 22. for new LUT `wild dog types`, can we add this endpoint in the source as well https://core.vocabs.paratoo.tern.org.au/api/lut-pest-wild-dogs?
- [ ] 23. for LUT `scat removal statuses`, can you please add this endpoint in the source as well? https://core.vocabs.paratoo.tern.org.au/api/lut-scats

**Comment by junrongYu** [comment]
Hi @arunherb , thanks for the updates, can you please have a look at following issues:
1. In this commit, https://github.com/ternaustralia/dawe-rlp-vocabs/pull/562/commits/7a00c23af472766a9032cfc5ae687df31bfbedee, need to add attribute `transect id`, but attribute `transect ID code` was added;
2. For OPs `fauna sign comments` and `fauna sign presence`, can you please remove the `tern:valueType` in concept files, cuz it's defined in metadata files;
3. In `within plot` and `off plot`, the metadata files of OP `fauna sign presence` should have `quadrat` as its feature type, the URI is http://linked.data.gov.au/def/tern-cv/4362c8f2-b3cc-4816-b5a2-fb7bb4c0cff5
4. In the new LUT `track station substrates`, for each metadata, values of `urnp:categoricalCollection` and `schema:url` are not correct; And looks like the metadata of concepts `sand ` and `tracking pad` are mixed, probably because they used the same metadata URI, can you please fix it?
5. Can you please remove the `tern:isAttributeOf` in the concept file of OP `fauna sign comments` cuz it was converted to OP, not attribute now;
6. In the concept file for attribute `fauna track photo ID`, `tern:Sample` and `tern:FeatureOfInterest` are both values of `tern:isAttributeOf`, can you please fix it?
Thanks!

**Comment by arunherb** [comment]
> Hi @arunherb , thanks for the updates, can you please have a look at following issues:
> 
> 1. In this commit, [7a00c23](https://github.com/ternaustralia/dawe-rlp-vocabs/commit/7a00c23af472766a9032cfc5ae687df31bfbedee), need to add attribute `transect id`, but attribute `transect ID code` was added; - **DONE**
> 2. For OPs `fauna sign comments` and `fauna sign presence`, can you please remove the `tern:valueType` in concept files, cuz it's defined in metadata files; **Done**
> 3. In `within plot` and `off plot`, the metadata files of OP `fauna sign presence` should have `quadrat` as its feature type, the URI is http://linked.data.gov.au/def/tern-cv/4362c8f2-b3cc-4816-b5a2-fb7bb4c0cff5 **Done**
> 4. In the new LUT `track station substrates`, for each metadata, values of `urnp:categoricalCollection` and `schema:url` are not correct; And looks like the metadata of concepts `sand ` and `tracking pad` are mixed, probably because they used the same metadata URI, can you please fix it?**Done**
> 5. Can you please remove the `tern:isAttributeOf` in the concept file of OP `fauna sign comments` cuz it was converted to OP, not attribute now; **Done**
> 6. In the concept file for attribute `fauna track photo ID`, `tern:Sample` and `tern:FeatureOfInterest` are both values of `tern:isAttributeOf`, can you please fix it? **Done**
>    Thanks!

**Comment by junrongYu** [comment]
Hi @arunherb , thanks for the updates, looks like the file path in `schema:url` for metadata is still wrong, can you please fix it?

**Comment by arunherb** [comment]
> Hi @arunherb , thanks for the updates, looks like the file path in `schema:url` for metadata is still wrong, can you please fix it? for LUT `track substrate types`

Thanks for checking this. I have fixed it now.

**Review by junrongYu — APPROVED** [review]

**Pull request merged**
