### PR TITLE
Improved methods `targeted survey`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #43

### CODE REVIEW

**Comment by junrongYu** [comment]
For this comment https://docs.google.com/document/d/18cnpymblK0JlO_vfBklYV2wvzMjsl4CO/edit?disco=AAAAcFHVYE8, we need to consider whether `Desktop study` is a submodule cuz it's not during the field survey and doesn't have any attribute or property. 
Currently it's in `Module overview` with the predicate `dcterms:description`.

**Comment by arunherb** [comment]
Here's some observations from the targeted survey protocol :

Like other modules lets use the following structure:
* Contents (with jump to liking all sections of the module)
* -> Introduction
* -> Key Definition
* ->Rationale
* ->Module overview
* sub-modules/sub-chapters (hyperlink all "skos:member")
* -> Desktop study
* ->References
* -> Appendix 

2) Can we make the appendix from the main page appear on a new page? because it is quite lengthy and can be annoying for field ecologists to scroll up and down.
3) Make sure all other links are working well.

**Comment by arunherb** [comment]
> Here's some observations from the targeted survey protocol :
> 
> Like other modules lets use the following structure:
> 
> * Contents (with jump to liking all sections of the module)
> * -> Introduction
> * -> Key Definition
> * ->Rationale
> * ->Module overview
> * sub-modules/sub-chapters (hyperlink all "skos:member")
> * -> Desktop study
> * ->References
> * -> Appendix
> 
> 2. Can we make the appendix from the main page appear on a new page? because it is quite lengthy and can be annoying for field ecologists to scroll up and down.
> 3. Make sure all other links are working well.

@junrongYu 
1) Under Fauna protocol hyperlink
a) "Vertebrate Fauna" and "Invertebrate Fauna" under additional guidelines and close the bracket at the end "(are prepared in advance."; b) under sub-heading B. Field survey - hyperlink "_opportune module_" as "_opportunistic observation module_" ; c) Under appendices hyperlink "_Vertebrate fauna Module_"  
2) Under Fauna - Active: hyperlink pt 9 and additional guide lines "Opportune module." and like above "Vertebrate Fauna" and "Invertebrate Fauna" under additional guidelines (same with Fauna - passive).
3) Under Flora - see additional guidelines section B. hyperlink "opportune module" (make it "_opportunistic observations_" as above) and section D. "_Floristics_ module" and "_Plant tissue vouchering_ module".

All other seems to be okay for this version.

**Review by edmondchuc — APPROVED** [review]
LGTM

**Pull request merged**
