### PR TITLE
Methods for `plot selection and layout` updated

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #48

### CODE REVIEW

**Comment by junrongYu** [comment]
Hyperlink for module `interventions` not added yet because not created.

**Comment by arunherb** [comment]
DAWE Protocols: "Plot Selection module" Review update.

1) Hyperlink "intervention module"; 2) Make sure all the links to Figures numbers, appendices and other modules that appear in text are working.
All other seems to be fine for this version.

**Comment by junrongYu** [comment]
Hi @arunherb ,

> Hyperlink "intervention module"

`intervention` methods not created yet, so cannot be added now, will add it later.

**Comment by arunherb** [comment]
> DAWE Protocols: "Plot Selection module" Review update.
> 
> 1. Hyperlink "intervention module"; 2) Make sure all the links to Figures numbers, appendices and other modules that appear in text are working.
>    All other seems to be fine for this version.

This module looks alright. No changes required at this stage :)

**Pull request merged**
