### PR TITLE
Set-1 LUTs Updates

### PR DESCRIPTION
**Pull request by arunherb**
This branch is for updating the Set-1 LUTs with discrepancies identified during mapping version-1 to version-2

### CODE REVIEW

**Comment by junrongYu** [comment]
Hi @arunherb , can you please update the value type of `plot reference point` and `fauna plot reference point` to `tern:IRI`, their values are IRIs with geometry details. Thanks.

**Comment by arunherb** [comment]
> Hi @arunherb , can you please update the value type of `plot reference point` and `fauna plot reference point` to `tern:IRI`, their values are IRIs with geometry details. Thanks.

Hi @junrongYu - this has been completed. The commit has been pushed to this branch.

**Comment by junrongYu** [comment]
Hi @arunherb , can you please clarify where the new attribute `disturbance history status` is used? It looks similar to the OP `site disturbance`.

**Comment by junrongYu** [comment]
> > Hi @arunherb , can you please clarify where the new attribute `disturbance history status` is used? It looks similar to the OP `site disturbance`.
> 
> Hi @junrongYu - this was created to distinguish the status of the disturbance history, i.e., whether the data on disturbance history is known or unknown while describing the plot.

Hi @arunherb , where is it in the protocol? OP `fire history` has `known` and `unknown` as the LUT values now.

**Comment by arunherb** [comment]
> > > Hi @arunherb , can you please clarify where the new attribute `disturbance history status` is used? It looks similar to the OP `site disturbance`.
> > 
> > 
> > Hi @junrongYu - this was created to distinguish the status of the disturbance history, i.e., whether the data on disturbance history is known or unknown while describing the plot.
> 
> Hi @arunherb , where is it in the protocol? OP `fire history` has `known` and `unknown` as the LUT values now.

Hi @junrongYu - yes it is referring to 'fire history status'. Not sure why it was named as disturbance history. Can you plkease updated this to 'fire history status' and the definition to 'the status of fire history, i.e., 'known' or 'unknown'. Thanks

**Comment by junrongYu** [comment]
> > > > Hi @arunherb , can you please clarify where the new attribute `disturbance history status` is used? It looks similar to the OP `site disturbance`.
> > > 
> > > 
> > > Hi @junrongYu - this was created to distinguish the status of the disturbance history, i.e., whether the data on disturbance history is known or unknown while describing the plot.
> > 
> > 
> > Hi @arunherb , where is it in the protocol? OP `fire history` has `known` and `unknown` as the LUT values now.
> 
> Hi @junrongYu - yes it is referring to 'fire history status'. Not sure why it was named as disturbance history. Can you plkease updated this to 'fire history status' and the definition to 'the status of fire history, i.e., 'known' or 'unknown'. Thanks

@arunherb , if it's the same as OP `fire history`, we can deprecate this new file, what do you think?

**Comment by arunherb** [comment]
> > > > > Hi @arunherb , can you please clarify where the new attribute `disturbance history status` is used? It looks similar to the OP `site disturbance`.
> > > > 
> > > > 
> > > > Hi @junrongYu - this was created to distinguish the status of the disturbance history, i.e., whether the data on disturbance history is known or unknown while describing the plot.
> > > 
> > > 
> > > Hi @arunherb , where is it in the protocol? OP `fire history` has `known` and `unknown` as the LUT values now.
> > 
> > 
> > Hi @junrongYu - yes it is referring to 'fire history status'. Not sure why it was named as disturbance history. Can you plkease updated this to 'fire history status' and the definition to 'the status of fire history, i.e., 'known' or 'unknown'. Thanks
> 
> @arunherb , if it's the same as OP `fire history`, we can deprecate this new file, what do you think?

Hi @junrongYu , I remember the app team using this to indicate that the data is known/collected. It is better to confirm with them before depreciating.

**Comment by junrongYu** [comment]
Hi @arunherb , in LUT `life stages`, the metadata of concept `immature Fruit` was deleted, but it's in Paratoo endpoint https://core.vocabs.paratoo.tern.org.au/api/lut-condition-life-stages, should we bring it back?

**Comment by arunherb** [comment]
> Hi @arunherb , in LUT `life stages`, the metadata of concept `immature Fruit` was deleted, but it's in Paratoo endpoint https://core.vocabs.paratoo.tern.org.au/api/lut-condition-life-stages, should we bring it back?

Hi @junrongYu - yes, I think we should bring it back. Thanks

**Comment by junrongYu** [comment]
Hi @arunherb , in LUT `observation method tier 2`, the definition of LUT concept `spotlighting` is "Spotlighting technique is a method used for fauna observations during the night and assists sur", is it complete?

**Comment by arunherb** [comment]
> Hi @arunherb , in LUT `observation method tier 2`, the definition of LUT concept `spotlighting` is "Spotlighting technique is a method used for fauna observations during the night and assists sur", is it complete?

Hi @junrongYu  - you can update this to "Spotlighting technique is a method used for fauna observations during the night and assists surveyors target nocturnal animals, using off-road vehicles and high-powered lights, spotlights, lamps or flashlights."

**Comment by junrongYu** [comment]
Hi @arunherb , notation `DN` is added for concept `DNA`, is it from endpoints?

**Comment by arunherb** [comment]
@junrongYu - yes it is the notation mentioned in the LUT API "https://core.vocabs.paratoo.tern.org.au/api/lut-tier-2-observation-methods"

**Comment by junrongYu** [comment]
Hi @arunherb , most of observation method concepts are added with prefix, why the prefix is removed from method `shell`, is it used somewhere else?

**Comment by arunherb** [comment]
> Hi @arunherb , most of observation method concepts are added with prefix, why the prefix is removed from method `shell`, is it used somewhere else?

@junrongYu - Shell is used in 'observation method -tier-2' (https://core.vocabs.paratoo.tern.org.au/api/lut-tier-2-observation-methods). We are removing the prefix for such concepts and defining the concept per se, i.e., what the 'Shell' refers to. We add prefix only for any concept that is duplicated but has slightly different definition/use-case or in instances  that uses unique identifier codes (for example: https://linked.data.gov.au/def/nrm/bf0e07c4-0977-4a97-9e82-11691641ca2e). Also, can you please review the tier-3 LUTs it seems to be out-of-sync with the API. We may have to update them?

**Comment by junrongYu** [comment]
> > Hi @arunherb , most of observation method concepts are added with prefix, why the prefix is removed from method `shell`, is it used somewhere else?
> 
> @junrongYu - Shell is used in 'observation method -tier-2' (https://core.vocabs.paratoo.tern.org.au/api/lut-tier-2-observation-methods). We are removing the prefix for such concepts and defining the concept per se, i.e., what the 'Shell' refers to. We add prefix only for any concept that is duplicated but has slightly different definition/use-case or in instances that uses unique identifier codes (for example: https://linked.data.gov.au/def/nrm/bf0e07c4-0977-4a97-9e82-11691641ca2e). Also, can you please review the tier-3 LUTs it seems to be out-of-sync with the API. We may have to update them?

Hi @arunherb , does that mean all these prefixes added in this branch should be removed? like this
Screenshot 2024-08-20 at 10 09 39 AM
Yes tier 3 is out of sync, current API values make more sense than just codes.

**Comment by arunherb** [comment]
@junrongYu - No. You can keep the changes that I have proposed for now for those prefixes. This is because in some cases like 'basal sweep sampling point', we need to distinguish the NW, SW, SE, etc. compass direction codes from corner points or sampling locations. Or the concepts hat uses 'Mature', "Recently Shed', "Juvenile', etc.  from 'plant life stages' and 'phenological stages'; or growth forms that uses NVIS defined categories. Hence, we have used them in that way.

**Comment by junrongYu** [comment]
> @junrongYu - No. You can keep the changes that I have proposed for now for those prefixes. This is because in some cases like 'basal sweep sampling point', we need to distinguish the NW, SW, SE, etc. compass direction codes from corner points or sampling locations. Or the concepts hat uses 'Mature', "Recently Shed', "Juvenile', etc. from 'plant life stages' and 'phenological stages'; or growth forms that uses NVIS defined categories. Hence, we have used them in that way.
> 
> Will you be able to update the tier-3 values that we already have?

yes, I am resolving duplicate LUT concepts for now, will update the tier 3 collection later

**Comment by junrongYu** [comment]
Hi @arunherb , the prefix `compass direction` is added for concept `East`, but the concept is used in multiple LUTs, here are the details:

**Concept**
https://linked.data.gov.au/def/nrm/0cad1fc8-0741-5dc8-90f5-7a4c6c7fba5f: compass direction - East
**Collections**:

-   https://linked.data.gov.au/def/nrm/96d41885-70e5-44c1-bafc-73027f47941b: Basal sweep sampling points
-   https://linked.data.gov.au/def/nrm/2742ccd6-cbe7-406c-a4aa-265944774454: Camera trap points
-   https://linked.data.gov.au/def/nrm/232d5fdd-c15f-4a84-865e-46ea20b82ff1: Direction codes

Does it make sense for all these 3 LUTs?

**Comment by arunherb** [comment]
> https://linked.data.gov.au/def/nrm/0cad1fc8-0741-5dc8-90f5-7a4c6c7fba5f

Hi @junrongYu - the concept 'North, 'South', 'East' and 'West' are used for 'direction codes', with reference to its **compass/cardinal directions**; versus the sampling points (i.e, basal sweep, plot corners, camera trap points) in the plot, which is nothing but the **spatial points** relative to the plot centre. I think we need to separate the 'East' used in 'Direction Codes' versus others referring to as : 'sampling point - East'; 'camera trap point - East'. And update the definition/s 'East' - refers to cardinal or compass direction'; 'sampling point - East' - refers to the spatial point in the east-end of the plot where a 360 degree basal sweep sampling is conducted; 'camera trap point - East' - refers to the spatial point in the east-end of the plot where the camera trap is deployed. 

Can you please update this and the definition/s if possible for all these occurrences (including, West, South, North etc.)? If it is a big task, please let me know, I'll update them and push it in the same branch.

**Comment by junrongYu** [comment]
> > https://linked.data.gov.au/def/nrm/0cad1fc8-0741-5dc8-90f5-7a4c6c7fba5f
> 
> Hi @junrongYu - the concept 'North, 'South', 'East' and 'West' are used for 'direction codes', with reference to its **compass/cardinal directions**; versus the sampling points (i.e, basal sweep, plot corners, camera trap points) in the plot, which is nothing but the **spatial points** relative to the plot centre. I think we need to separate the 'East' used in 'Direction Codes' versus others referring to as : 'sampling point - East'; 'camera trap point - East'. And update the definition/s 'East' - refers to cardinal or compass direction'; 'sampling point - East' - refers to the spatial point in the east-end of the plot where a 360 degree basal sweep sampling is conducted; 'camera trap point - East' - refers to the spatial point in the east-end of the plot where the camera trap is deployed.
> 
> Can you please update this and the definition/s if possible for all these occurrences (including, West, South, North etc.)? If it is a big task, please let me know, I'll update them and push it in the same branch.

Hi @arunherb , we can customise their definitions in metadata instead of creating separate concepts, that's why we use metadata to manage the same concept in multiple collections, can you please list its definitions in three LUTs? I can add them.

**Comment by arunherb** [comment]
> > > https://linked.data.gov.au/def/nrm/0cad1fc8-0741-5dc8-90f5-7a4c6c7fba5f
> > 
> > 
> > Hi @junrongYu - the concept 'North, 'South', 'East' and 'West' are used for 'direction codes', with reference to its **compass/cardinal directions**; versus the sampling points (i.e, basal sweep, plot corners, camera trap points) in the plot, which is nothing but the **spatial points** relative to the plot centre. I think we need to separate the 'East' used in 'Direction Codes' versus others referring to as : 'sampling point - East'; 'camera trap point - East'. And update the definition/s 'East' - refers to cardinal or compass direction'; 'sampling point - East' - refers to the spatial point in the east-end of the plot where a 360 degree basal sweep sampling is conducted; 'camera trap point - East' - refers to the spatial point in the east-end of the plot where the camera trap is deployed.
> > Can you please update this and the definition/s if possible for all these occurrences (including, West, South, North etc.)? If it is a big task, please let me know, I'll update them and push it in the same branch.
> 
> Hi @arunherb , we can customise their definitions in metadata instead of creating separate concepts, that's why we use metadata to manage the same concept in multiple collections, can you please list its definitions in three LUTs? I can add them.

@junrongYu - Yes that makes sense.
1. **direction codes**: N, S, E, W NE, SE, NW, SW. Make sure they are all using the uppercase for first part of word (i.e. North West instead of Northwest).
N- Denotes the cardinal direction towards north (0° = 360°), a compass needle points to as it aligns with the Earth's magnetic field.
S- Denotes the cardinal direction towards the south (180°), directly opposite to the north .
E- Denotes the cardinal direction towards the to the right when facing North (90°) and is where the sun rises.
W - Denotes the cardinal direction towards the to the to the left (270°) when facing North and is where the sun sets.
NE - Denotes the cardinal direction (45°), halfway between north and east, is the opposite of southwest.  
SE -  Denotes the cardinal direction (135°), halfway between south and east, is the opposite of northwest.
SW - Denotes the cardinal direction (225°), halfway between south and west, is the opposite of northeast.
NW - Denotes the cardinal direction (315°), halfway between north and west, is the opposite of southeast.
2. **basal sweep sampling points**: 
'North' - The spatial point location which represents the cardinal direction at the 'north' end of the study plot, where sampling is conducted.   
'South' - The spatial point location which represents the cardinal direction at the 'south' end of the study plot, where sampling is conducted.
'East' -  The spatial point location which represents the cardinal direction at the 'east' end of the study plot, where sampling is conducted.   
'West' - The spatial point location which represents the cardinal direction at the 'west' end of the study plot, where sampling is conducted.
'South East' - The spatial point location which represents the cardinal direction at the 'southeast' corner of the study plot, where sampling is conducted.
'South West' - The spatial point location which represents the cardinal direction at the 'southwest' corner of the study plot, where sampling is conducted.
'North East' - The spatial point location which represents the cardinal direction at the 'northeast' corner of the study plot, where sampling is conducted.
'North West' - The spatial point location which represents the cardinal direction at the 'northwest' corner of the study plot, where sampling is conducted.
3. **plot corner-and-centre**:
'Centre' - The spatial point location, denoting the 'Centre' of the study plot and is equidistant from the plot corners.
'South East' - The spatial point location which represents the cardinal direction at the 'southeast' corner of the study plot.
'South West' - The spatial point location which represents the cardinal direction at the 'southwest' corner of the study plot. 
'North East' - The spatial point location which represents the cardinal direction at the 'northeast' corner of the study plot. 
'North West' - The spatial point location which represents the cardinal direction at the 'northwest' corner of the study plot.
4. **camera trap points** : Looks like this is no-longer a LUT. Please check

**Review by junrongYu — APPROVED** [review]

**Pull request merged**
