### PR TITLE
Improved methods for `recruitment`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #38

### CODE REVIEW

**Comment by arunherb** [comment]
Some comments on the Recruitment module on local host:
1) The hyperlinks for other modules need to be updated; 
2)Can we have it in the following order:
* Contents
* -> Introduction
* ->Key definition
* ->Rationale
* ->Module overview
* sub-chapters/modules (with hyperlinks)
* -> References
* -> Appendices

3) Also, I'm wondering if we can make all the appendices for all of the modules to appear on a new page- just like how the sub-modules / sub-chapters appear? Because the main page will look more presentable and easy to scroll for field ecologists rather than having some wonky images with a different dimension appear in the main page. This is just a thought, but we can probably also leave it as is for this version and update these aesthetics in future versions.

4) Make sure all other hyperlinks are working well.

**Comment by arunherb** [comment]
> Some comments on the Recruitment module on local host:
> 
> 1. The hyperlinks for other modules need to be updated;
>    2)Can we have it in the following order:
> 
> * Contents
> * -> Introduction
> * ->Key definition
> * ->Rationale
> * ->Module overview
> * sub-chapters/modules (with hyperlinks)
> * -> References
> * -> Appendices
> 
> 3. Also, I'm wondering if we can make all the appendices for all of the modules to appear on a new page- just like how the sub-modules / sub-chapters appear? Because the main page will look more presentable and easy to scroll for field ecologists rather than having some wonky images with a different dimension appear in the main page. This is just a thought, but we can probably also leave it as is for this version and update these aesthetics in future versions.
> 4. Make sure all other hyperlinks are working well.

@junrongYu 
Ignore pt 3 above for now. 

1) Can we hyperlink all the other modules that appear in the sub-module section
2) Can we hyperlink _Plot selection and layout_ module and "_cover_" module that appear in the age class sub-protocol. Also, "_Condition_" in Additional guidelines.
3) In Appendices-1 section, the "recently shed" images are missing.

Arun

**Comment by junrongYu** [comment]
Hi @arunherb ,

> In Appendices-1 section, the "recently shed" images are missing.

It is blank in the original image.

> Can we hyperlink all the other modules that appear in the sub-module section

Could you please list all locations which need hyperlinks while reviewing? Otherwise it may take me the same time to find them. Thanks!

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> > In Appendices-1 section, the "recently shed" images are missing.
> 
> It is blank in the original image.
> (Perhaps we should check with Sally's team to provide an updated image)
> > Can we hyperlink all the other modules that appear in the sub-module section
> 
> Could you please list all locations which need hyperlinks while reviewing? Otherwise it may take me the same time to find them. Thanks!

Its , "A. Growth stage and life-stage
Ensure the _Plot selection and layout_"
"C.Small tree survey .... 
pt number 1. Ensure the _Plot selection and layout module_ "
Under "Additional guidelines, see ....._Condition module_..."

**Comment by junrongYu** [comment]
Hi @arunherb , 

Thanks a lot! I've added those hyperlinks, could you please list them in such a way for other protocols as well? TIA!

**Review by edmondchuc — APPROVED** [review]

**Pull request merged**
