### PR TITLE
Improved methods `invertebrate fauna`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #41

### CODE REVIEW

**Comment by junrongYu** [comment]
`General survey guidelines` is not added because it'll be provided in the PDF, like `pre-field survey` or `post-field survey`.

**Comment by arunherb** [comment]
Hi @junrongYu ,

Here's some observations from the Invertebrate fauna on the localhost pdf:
1) Can we put this in the following order: 
* Contents 
* -> Introduction
* -> Key definition
* -> Rationale
* ->Module overview 
* -> **sub-module names ("skos:member")** with hyperlinks
* -> References
* ->Appendix

2)  "_Appendix_" can be removed from themain page if there is no reference to it in the introduction, rationale, etc. and let it only be in the sub-modules where they refer to it frequently. 
3) We need to check, whether we keep "_opportunistic observations module_" as "_opportune_" and homogenise the module title accordingly, where they appear.
4) Under the Lepi-LED light trapping protocols there are hyperlinks for some of the Equipments. Wondering what is it linking to?

Other contents seem alright for this first version.

**Comment by junrongYu** [comment]
> "Appendix" can be removed from themain page if there is no reference to it in the introduction, rationale, etc. and let it only be in the sub-modules where they refer to it frequently

Hi @arunherb , these 2 appendices are put in each page cuz I thought they are some general information that may be referred. If you think they are not useful in most cases, we can deleted them where not referred. 

Also, I just found this sentence in the main page, `Decision trees are provided in the Appendix to help with the selection of the most suitable protocol/s.`, but you didn't add the decision tree in the Google doc, does that mean this sentence can be deleted?

> We need to check, whether we keep "opportunistic observations module" as "opportune" and homogenise the module title accordingly, where they appear.

Yes, Jeremy called it `opportune`, but I am not sure whether it's the official name, we can discuss it with protocols team later.

> Under the Lepi-LED light trapping protocols there are hyperlinks for some of the Equipments. Wondering what is it linking to?

They are some external links from the protocol file, seems to be some description of these equipments. If you are interested, we can have a review together.

**Comment by arunherb** [comment]
> > "Appendix" can be removed from themain page if there is no reference to it in the introduction, rationale, etc. and let it only be in the sub-modules where they refer to it frequently
> 
> Hi @arunherb , these 2 appendices are put in each page cuz I thought they are some general information that may be referred. If you think they are not useful in most cases, we can deleted them where not referred.
> 
> Also, I just found this sentence in the main page, `Decision trees are provided in the Appendix to help with the selection of the most suitable protocol/s.`, but you didn't add the decision tree in the Google doc, does that mean this sentence can be deleted?
> 
> > We need to check, whether we keep "opportunistic observations module" as "opportune" and homogenise the module title accordingly, where they appear.
> 
> Yes, Jeremy called it `opportune`, but I am not sure whether it's the official name, we can discuss it with protocols team later.
> 
> > Under the Lepi-LED light trapping protocols there are hyperlinks for some of the Equipments. Wondering what is it linking to?
> 
> They are some external links from the protocol file, seems to be some description of these equipments. If you are interested, we can have a review together.

Hi @junrongYu ,

1) I think you can leave the appendices the way it is for now. 
Under appendices
- I noticed that there is a mention of "Preservative %age" - it should be "Preservative concentration" I think?
- Also, can we make the "Trap elevation ASL" to "Trap elevation asl".

2) For "opportune module", let us call it "opportunistic observations module" as it says in that module. 
3) Can we hyperlink the sub-module names that appear in the instructions page of each sub-module. Also, see pt 40 in Wet micropitfall, there is name error, it says " .....Micro-pitall trap ID" and should be "Micro-pitfall trap ID.."  .
4) Under the Leaf litter protocol, see  the hyperlinks for "litter reducer/litter sifter" under Rationale. It gives an error. Better to remove the hyperlink if it is not linking to the right link. 
5) Under the sub-module Lepi-led- complete the sentence "[Battery packs](https://www.entosupplies.com.au/) or 12 V car battery as a power source for the LepiLED available from **Australian Entomological Supplies Pvt Ltd**".
6) Under Post-field guideline protocol, can we make the "Additional Guidelines" a "skos:note" concept?
7) Also there's some information in the Appendices related to the sub-modules, "Foliar beating" and "Sweep net". We should probably ask Sally's team to review this and check with them if they provide an updated version of this appendices?

Others look alright for this version.

Arun

**Review by edmondchuc — APPROVED** [review]

**Pull request merged**
