### PR TITLE
Fix the property `plant status`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #87

### CODE REVIEW

**Comment by junrongYu** [comment]
The source, definition, and feature type need to be confirmed.

**Comment by junrongYu** [comment]
Here, the value type for `plant status` is `boolean` https://docs.google.com/spreadsheets/d/1JXP16wh1IG4i9-mdL_xOCJc60Y6vhQMiloCV0d0SIjw/edit#gid=1709262829&range=L56. However, the value type for `tree status`, `tree alive status`, and `plant alive status` are all categorical, and  3 different categorical APIs all have at least 3 values.

**Comment by arunherb** [comment]
> Here, the value type for `plant status` is `boolean` https://docs.google.com/spreadsheets/d/1JXP16wh1IG4i9-mdL_xOCJc60Y6vhQMiloCV0d0SIjw/edit#gid=1709262829&range=L56. However, the value type for `tree status`, `tree alive status`, and `plant alive status` are all categorical, and 3 different categorical APIs all have at least 3 values.

Hi @junrongYu 
I think we originally had it as "**plant alive status**", which is a boolean (Yes/No)
But, after we updated to "**plant status**" we it becomes categorical, with values "Alive" and "Dead".
So just keep "plant status" and make it a categorical value.

Thanks,
Arun

**Comment by junrongYu** [comment]
The feature type is `plant individual`.

**Review by edmondchuc — APPROVED** [review]

**Pull request merged**
