### PR TITLE
`label` updated to `identification label`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #73

### CODE REVIEW

**Comment by edmondchuc** [comment]
I don't think we need this attribute. There exists `dwc:materialSampleID` on the `tern:MaterialSample` class.

**Comment by junrongYu** [comment]
> I don't think we need this attribute. There exists `dwc:materialSampleID` on the `tern:MaterialSample` class.
> 
> See https://w3id.org/tern/ontologies/tern/MaterialSample

That make sense, if so, we may need to delete other similar attributes, should I create an issue for this?

**Comment by edmondchuc** [comment]
Not sure what the issue will represent. We probably have to do a thorough review and see what needs to be removed. This review will likely take place when we work on the mapping between the app JSON data to the TERN Ontology.

**Comment by junrongYu** [comment]
> Not sure what the issue will represent. We probably have to do a thorough review and see what needs to be removed. This review will likely take place when we work on the mapping between the app JSON data to the TERN Ontology.

Yeah, more issues will be found through the mapping, so let's delete this attribute for now?

**Comment by edmondchuc** [comment]
Yeah sounds good. We can close this PR and create a new one where we delete this attribute.

**Pull request closed without merging**
