### PR TITLE
Improved methods `soil`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #40

### CODE REVIEW

**Comment by junrongYu** [comment]
All `post-field survey` not added because they'll be provided in the PDF link.

**Comment by junrongYu** [comment]
Add the YB link.
https://docs.google.com/document/d/1hCpIdo8Kilyhn3rqk5nIPali_IQE4dEQ/edit?disco=AAAAdXNsMco

**Comment by junrongYu** [comment]
The link of `interventions` modules not added because not created yet.

**Comment by junrongYu** [comment]
Content needs to be updated by the protocols team.
https://docs.google.com/document/d/1hCpIdo8Kilyhn3rqk5nIPali_IQE4dEQ/edit?disco=AAAAdXNsMfc

**Comment by arunherb** [comment]
Just like other modules:
1) Can we have it in the following order:
* Contents (with a jump to link for each section)
* -> Introduction
* -> Key definition
* -> Rationale
* ->Module overview
* sub-modules/sub-chapters (with hyperlinks "skos:member")
* ->References
* ->Appendices

2) Can we keep the appendix in another page? Because there are so many codes and abbreviations from the yellow book. We may need to keep them as distinct that appear on new page. Same with the sub-modules.

3) Make sure all the other hyperlinks to other modules are working fine. 

The other aspects for this version look good for this version.

**Comment by arunherb** [comment]
> Just like other modules:
> 
> 1. Can we have it in the following order:
> 
> * Contents (with a jump to link for each section)
> * -> Introduction
> * -> Key definition
> * -> Rationale
> * ->Module overview
> * sub-modules/sub-chapters (with hyperlinks "skos:member")
> * ->References
> * ->Appendices
> 
> 2. Can we keep the appendix in another page? Because there are so many codes and abbreviations from the yellow book. We may need to keep them as distinct that appear on new page. Same with the sub-modules.
> 3. Make sure all the other hyperlinks to other modules are working fine.
> 
> The other aspects for this version look good for this version.


@junrongYu 
Hyperlink all the modules listed in italics below :
1) Under Module overview, 
a "_Plot description module_"; b) "....at the same time vegetation modules (e.g. _Floristics, Cover_)..."; c) pt 23, ".. return to the _Soils_ module"
2) Under plot soil description module see instructions pt 1 and pt 8 ".._plot selection and layout module_";  
3) Under Soil Pit Characterisation module 
a) see instructions ".._Plot selection and layout module_"; 
b) see pt n4, " .. soil pit characterisation and soil sample collection", and "soil sample collection"- can we remove the underline from collection in both cases.
c) see pt n44 ".._Soils_.." and under B. Soil sample collection see pt 18".._Soils_ .." 
3)under soil bulk density protocol, a) see instructions pt 1 "_Plot selection and layout module_" and pt 2"_Soil Pit Characterisation protocol_"; b) see pt 22 ".._Soils module_."
4) under Soil condition module, see instructions, pt 1, "..Plot selection and layout module .."
5) Under Soil metagenomics module, 
see Protocol Overview, "_soil sub-site characterisation_ protocol" and b) see instructions for "_Plot selection and layout_" and pt 19 for "_Soils_ module".   

All others seem to be alright. We should see in future versions whether we add the Bulk density calculations or not.

Arun

**Review by edmondchuc — APPROVED** [review]
LGTM

**Pull request merged**
