### PR TITLE
Fix methods `plot description`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #47

### CODE REVIEW

**Comment by edmondchuc** [comment]
In Jira, these are the two issues that need to be fixed:

1. There are Figures and Appendix reference in thetext, but we do not know which figures they are referring to and also no appendix listed here.
2. Can we also maintain numbering/bullet points consistent across modules? Like here we use "..a, b, c..", instead of "i, ii, ii, etc.."

Does this PR fix those issues?

**Comment by junrongYu** [comment]
Hi @edmondchuc , figure reference is okay here, and I just fixed the Appendix reference. I'll check other improved methods as well because sometimes I forgot this.
I am not sure about numbering in the new structure, but it looks good for `basal area`, so I think it should be okay as long as we stick to the structure.

**Review by edmondchuc — APPROVED** [review]

**Comment by junrongYu** [comment]
plot-description

**Comment by arunherb** [comment]
DAWE Protocols: **Plot Description Module** localhost review feedback

1) User-end specifications- I was wondering whether it might be worth introducing a list of contents at the very beginning (after the main title) for each description property listed in the protocol. This will be a good incentive for field-based studies because ecologists using the app can jump directly to the section they are interested, such as "introduction", "rationale", "Module overview", etc., especially in lengthy modules;
2) Make sure all the hyperlinks for Figure numbers, Appendix, other modules that appear in text are hyperlinked to their respective ones. 
All others seems alright for now. 

Cheers,
Arun

**Pull request merged**
