### PR TITLE
Improved methods for `plant tissue vouchering`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #46

### CODE REVIEW

**Comment by arunherb** [comment]
@junrongYu ,

In this module there is figure 1  that refers to a plant tissue voucher specimen with a barcode, but says "QR code". I think we can leave it as such for now, but when they surveillance team review this module after the changes we discussed with them, we can update accordingly. 
As per our discussions today, we keep just 'voucher specimen id' across modules.

2) hyperlink "Floristics module" from the pt,4 in Instructions and procedures in the sub-module

All others seem alright for this version.

**Comment by junrongYu** [comment]
Hi @arunherb ,

> In this module there is figure 1 that refers to a plant tissue voucher specimen with a barcode, but says "QR code". I think we can leave it as such for now, but when they surveillance team review this module after the changes we discussed with them, we can update accordingly.

Should I update all `QR code` to `barcode` or `QR code/barcode`?

Thanks,
Junrong

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> > In this module there is figure 1 that refers to a plant tissue voucher specimen with a barcode, but says "QR code". I think we can leave it as such for now, but when they surveillance team review this module after the changes we discussed with them, we can update accordingly.
> 
> Should I update all `QR code` to `barcode` or `QR code/barcode`?
> 
> Thanks, Junrong

Hi @junrongYu ,

I think we can leave the QR code as "plant tissue id" for this particular module and barcode as "voucher specimen id". 
See the synonyms sheet we updated recently : https://docs.google.com/spreadsheets/d/1JXP16wh1IG4i9-mdL_xOCJc60Y6vhQMiloCV0d0SIjw/edit#gid=1709262829

Arun

**Comment by junrongYu** [comment]
Hi @arunherb ,

> I think we can leave the QR code as "plant tissue id" for this particular module and barcode as "voucher specimen id".

Yes, they are for synonyms, I mean for text like `QR code` or `barcode` in protocols, do we just leave it there?

Thanks,
Junrong

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> > I think we can leave the QR code as "plant tissue id" for this particular module and barcode as "voucher specimen id".
> 
> Yes, they are for synonyms, I mean for text like `QR code` or `barcode` in protocols, do we just leave it there?
> 
> Thanks, Junrong

Hi @junrongYu ,
Oh alright! I've added some text in red (https://uq-my.sharepoint.com/:w:/r/personal/uqsguru_uq_edu_au/_layouts/15/Doc.aspx?sourcedoc=%7B14E1ED63-7315-477C-8A17-0CA70185CAE4%7D&file=Plant%20Tissue%20Vouchering%20Module_DRAFT_v0_1.docx&action=default&mobileredirect=true). I think we can update this information and ask Sally's team to review the protocol and update it in their end.

**Comment by junrongYu** [comment]
Hi @arunherb , new changes look good, i'll update those 2 in `Full protocol`.

**Comment by arunherb** [comment]
> Hi @arunherb , new changes look good, i'll update those 2 in `Full protocol`.

@junrongYu 

1) See pt 7 under Lite protocol- it needs to be updated like the other module.
2) There is the spelling mistake I think in the original module. Can we make this "dominant perennail" under instructions to "_dominant perennial_"?

All others seem okay for this module
Arun

**Pull request merged**
