### PR TITLE
Integrate `flora health factor`, `health factors`, `vegetation health`, `health` to `vegetation health factor`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #26

### CODE REVIEW

**Comment by edmondchuc** [comment]
I think we should start adding to the `observable_property_by_module_meta.ttl` file each observable property's feature type etc for each module. Otherwise, this information is lost in the issues here. E.g. https://github.com/ternaustralia/dawe-rlp-vocabs/issues/26#issuecomment-1175625340

**Comment by junrongYu** [comment]
Yeah, I think so, so I add it to my notebook. 

> adding to the `observable_property_by_module_meta.ttl` file each observable property's feature type etc for each module

Do we need to figure out the structure together later?

**Comment by edmondchuc** [comment]
Let's try and follow this structure for now:

Same observable property used in different protocols.

```turtle
<https://linked.data.gov.au/def/nrm/c9491ae2-43aa-47d8-acf6-5373ff49df6d> a <urn:class:ObservablePropertyMeta> ;
    <urn:property:protocolModule> <https://linked.data.gov.au/def/test/dawe-cv/1ff9e97c-3bdd-44c9-bdd3-401fa31c0b32> ;
    <urn:property:observableProperty> <https://linked.data.gov.au/def/test/dawe-cv/132a1452-4fd7-473c-956b-3183dd315b67> ;
    <urn:property:featureType> <http://linked.data.gov.au/def/tern-cv/2cf3ed29-440e-4a50-9bbc-5aab30df9fcd> ;
    <urn:property:valueType> <https://w3id.org/tern/ontologies/tern/IRI> ;
    <urn:property:categoricalValuesCollection> <https://linked.data.gov.au/def/test/dawe-cv/d893e669-c530-4bc3-a057-a5799ffcb5db> ;
.

<https://linked.data.gov.au/def/nrm/27d6e257-7a72-4d7e-8238-203438575c84> a <urn:class:ObservablePropertyMeta> ;
    <urn:property:protocolModule> <https://linked.data.gov.au/def/test/dawe-cv/7818e122-6354-42e0-aeff-32dbab7baae4> ;
    <urn:property:observableProperty> <https://linked.data.gov.au/def/test/dawe-cv/132a1452-4fd7-473c-956b-3183dd315b67> ;
    <urn:property:featureType> <http://linked.data.gov.au/def/tern-cv/2cf3ed29-440e-4a50-9bbc-5aab30df9fcd> ;
    <urn:property:valueType> <https://w3id.org/tern/ontologies/tern/IRI> ;
    <urn:property:categoricalValuesCollection> <https://linked.data.gov.au/def/test/dawe-cv/d893e669-c530-4bc3-a057-a5799ffcb5db> ;
.

```

**Comment by edmondchuc** [comment]
@junrongYu can you fix the conflicts and get this branch up to date with main please?

**Review by edmondchuc — CHANGES_REQUESTED** [review]
Resolve conflicts please

**Pull request closed without merging**
