### PR TITLE
Fix methods `camera traps` and `cwd`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #39 
Fixes: #35

### CODE REVIEW

**Comment by junrongYu** [comment]
The link to `interventions` module is not added cuz not created yet.

**Comment by junrongYu** [comment]
The part `Analysis and calculations` is not added to `cwd` methods because it's after site visit, TBD whether to put in the PDF later.

**Comment by arunherb** [comment]
Hi @junrongYu ,
General feedback for the camera traps:
1) In Appendix B, please fix the "copyright symbol" to "C".
2) Make sure all the links are working for figure numbers, tables, appendix and sub-modules.
3) We should create a table of contents for each module (where we provide jump-to-section) for easy user-end operation for field ecology survey.

All others seem to be fine at this stage.
Arun

**Comment by arunherb** [comment]
CWD module seems to be fine on the localhost. 
Just make sure all the hyperlinks are working.

**Comment by junrongYu** [comment]
> In Appendix B, please fix the "copyright symbol" to "C".

Hi @arunherb , could you clarify where is the `copyright symbol`? I cannot find it in both our methods and the protocol file.

**Comment by arunherb** [comment]
> CWD module seems to be fine on the localhost. Just make sure all the hyperlinks are working.
@junrongYu ,

1) Can we add the section 6.. "Analysis and Calculation" from CWD module and hyperlink where it appears. It can be before the references at the end of module overview.
https://uq-my.sharepoint.com/:w:/r/personal/uqsguru_uq_edu_au/_layouts/15/Doc.aspx?sourcedoc=%7B225B0CB6-021F-4B90-A8F1-E41053473152%7D&file=Coarse%20woody%20debris%20module_DRAFT_v0.1.docx&action=default&mobileredirect=true 
2) Can we remove extra fullstops "..." after "...see Figure 4.." in the sub-protocol, pt number 5.

All other content seems to be okay for this version.

Arun

**Comment by arunherb** [comment]
> Hi @junrongYu , General feedback for the camera traps:
> 
> 1. In Appendix B, please fix the "copyright symbol" to "C".
> 2. Make sure all the links are working for figure numbers, tables, appendix and sub-modules.
> 3. We should create a table of contents for each module (where we provide jump-to-section) for easy user-end operation for field ecology survey.
> 
> All others seem to be fine at this stage. Arun

SOme more comments here:
1) In addition to above, can we hyperlink the sub-modules that appear under the "module overview" section?

Cheers
A

**Comment by junrongYu** [comment]
Hi @arunherb ,

> Can we add the section 6.. "Analysis and Calculation" from CWD module and hyperlink where it appears. It can be before the references at the end of module overview.

It's not added because it's not the field work? Later we'll make the protocol file available and the section can be fetched via the PDF link, is that suitable?

Thanks,
Junrong

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> > Can we add the section 6.. "Analysis and Calculation" from CWD module and hyperlink where it appears. It can be before the references at the end of module overview.
> 
> It's not added because it's not the field work? Later we'll make the protocol file available and the section can be fetched via the PDF link, is that suitable?
> 
> Thanks, Junrong

Hi @junrongYu ,

In that case, we should probably add a note in that text to refer to the protocol pdf file for analysis and calculations.

**Review by edmondchuc — APPROVED** [review]

**Pull request merged**
