### PR TITLE
Improve methods `Opportunistic observations`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #50

### CODE REVIEW

**Comment by junrongYu** [comment]
TBC with protocols team
https://uq-my.sharepoint.com/:w:/r/personal/uqsguru_uq_edu_au/Documents/TDSA/External%20Projects/DAWE%20DEAP%20Project/Surviellance%20protocol/1st%20set%20of%20modules%20as%20delivered%20May%202021/Updated_protocols_for_DAWE_Vocabs/Opportunistic%20Observations%20Module_DRAFT_v0_1_ASR_Edited.docx?d=w1c6b429aa39e4205ab3d3441bf8dd379&csf=1&web=1&e=fB3Uh2&nav=eyJjIjo0NDE5MjkwMH0%3D

**Comment by arunherb** [comment]
DAWE protocols: Opportunistic Observations: 
1) In App-mock-up screen, can we hyperlink ALA, IiNaturalist and WOW sites?;
2)Make sure all the links for figures and appendices are hyperlinking 

All others seem to be fine for this first version. 

Thanks
Arun

**Comment by junrongYu** [comment]
> In App-mock-up screen, can we hyperlink ALA, IiNaturalist and WOW sites?;

Hi @arunherb , thanks for the catch, could you give me the link to these 3? I cannot find related links in the protocol file.

**Comment by arunherb** [comment]
> > In App-mock-up screen, can we hyperlink ALA, IiNaturalist and WOW sites?;
> 
> Hi @arunherb , thanks for the catch, could you give me the link to these 3? I cannot find related links in the protocol file.

Hi @junrongYu ,
ALA: https://www.ala.org.au/
iNaturalist: https://www.inaturalist.org/
WOW: I'm not sure about this, we can leave it as it is, and ask Sally when she review's what they are referring to?

Arun

**Comment by junrongYu** [comment]
Hi @arunherb ,

Thanks for clarifying! 

> WOW: I'm not sure about this, we can leave it as it is, and ask Sally when she review's what they are referring to?

I'll add this comment in https://github.com/ternaustralia/dawe-rlp-vocabs/issues/203

**Comment by arunherb** [comment]
> Hi @arunherb ,
> 
> Thanks for clarifying!
> 
> > WOW: I'm not sure about this, we can leave it as it is, and ask Sally when she review's what they are referring to?
> 
> I'll add this comment in #203

@junrongYu 

1) With above, we should also ask Sally's team which "_Introduction chapter for guidance_" are they referring to?
2) Under module overview, second paragraph - hyperlink "_Vertebrate fauna, Invertebrate fauna, and Targeted survey modules_".
3) Also hyperlink "_Floristic, Vertebrate fauna, Invertebrate fauna and Targeted survey_", under Additional guidelines , pt C.; "_Plant tissue vouchering_", pt D. ; "_Vertebrate fauna module_", pt F. 

All others are fine for this version.

**Review by edmondchuc — APPROVED** [review]

**Pull request merged**
