### PR TITLE
Fix the property `dominant species`

### PR DESCRIPTION
**Pull request by junrongYu**
Fixes: #75

### CODE REVIEW

**Comment by edmondchuc** [comment]
What about the other ones mentioned in the original issue? E.g., "most dominant species", "second most dominant species", etc.

**Comment by edmondchuc** [comment]
What about third most dominant species?

**Comment by junrongYu** [comment]
> What about third most dominant species?

Hi @edmondchuc , do you know why `third most dominant species` is a property but not belonging to any module?

**Comment by edmondchuc** [comment]
From memory it was in the Plot Description module.

**Comment by junrongYu** [comment]
> From memory it was in the Plot Description module.

Cool, I'll update the property and link it in properties collection for `plot description`

**Review by edmondchuc — APPROVED** [review]

**Pull request merged**
